#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Styling, testing, and building your project before committing..."

# Check Prettier formatting
npm run check-format || {
    echo "Prettier Check Failed. Run 'npm run format', add changes, and try committing again."
    exit 1
}

# Check ESLint for linting issues
npm run check-lint || {
    echo "ESLint Check Failed. Make the required changes listed above, add changes, and try committing again."
    exit 1
}

# Check TypeScript configuration
npm run check-types || {
    echo "Type checking failed. Make the required changes listed above, add changes, and try committing again."
    exit 1
}

# Build the project
npm run build || {
    echo "Build failed. View the errors above."
    exit 1
}

echo "Commit successful!"
